### ISSUE TITLE
Metal texture buffer alignment workaround

### ISSUE THREAD

**Issue by 3Shain** [3Shain/dxmt#31]
Metal requires texture buffer created from buffer to be 16 bytes aligned. However DirectX doesn't have this restriction. Certain games indeed create consecutive SRVs on the same buffer, and the alignment is only 4 bytes. When validation layer is off, Metal is silent about this error and introduces incorrect shader read result.

Features to implement:

- Create texture buffer at nearest 16-bytes aligned address before the actually byte offset, and calculate the difference in bytes & elements
- Encode the elements diff in argument buffer (as a part of the descriptor) and let the shader take it into account and correct the address.

**Comment by K0bin** [comment]
Wasn't this requirement dropped with newer Metal versions on Apple GPUs?

**Comment by 3Shain** [comment]
> Wasn't this requirement dropped with newer Metal versions on Apple GPUs?

Nope
