### ISSUE TITLE
Add 32bit DLL in build artifacts.. (for perf testing of ComputeMark2 (DX11 32bit bench) vs DXVK)

### ISSUE THREAD

**Issue by oscarbg** [3Shain/dxmt#44]
Hi,
asked on discord:
```
can provide 32bit dlls in build artifacts? don't know if possible as Metal is 64 bit only but anyway DXVK macos provides 32bit d3d11.dll for example:
file dxmt/d3d11.dll
d3d11.dll: PE32+ executable (DLL) (GUI) x86-64, for MS Windows
but dxvk/x32/d3d11.dll
d3d11.dll: PE32 executable (DLL) (console) Intel 80386 (stripped to external PDB), for MS Windows
```

for example latest artifact:
>https://github.com/3Shain/dxmt/actions/runs/11719090299

has only 64bit DLL's
altough DXVK macOS ships with both 32bit dll and 64bit dll

>https://github.com/Gcenx/DXVK-macOS/releases
>https://github.com/Gcenx/DXVK-macOS/releases/tag/v1.10.3-20230507-repack

wanted for testing ComputeMark2 (32bit win exe)
app attached on:
>https://github.com/doitsujin/dxvk/issues/39

**Comment by 3Shain** [comment]
No, it requires a lot of work, not just done by switching a compiler flag.
