### ISSUE TITLE
Can't set EnvironmentVariables in cxbottle.conf

### ISSUE THREAD

**Issue by karpovpw** [3Shain/dxmt#50]
Setting

```
[EnvironmentVariables]
"DXMT_CONFIG_FILE" = "/Users/karpovpw/CXPBottles/11/dxmt.conf"
"DXMT_LOG_PATH" = "/Users/karpovpw/CXPBottles/11/dxmtLogs"
"DXMT_METALFX_SPATIAL_SWAPCHAIN" = "1"
```

doesn't do anything: no frame limiter (tried it in dxmt.conf), no logs and no metalFX. cxbottle.conf is for the correct bottle. CrossOver patched through CXPatcher.

Am I doing something wrong or are there other people who can't change EnvironmentVariables for dxmt?

The game is Metaphor:ReFantazio.

**Comment by 3Shain** [comment]
Please don't use our issue tracker for support of third party program.

**Comment by AndrewTriesToCode** [comment]
Worked for me usingL
`"DXMT_LOG_PATH" = "C:\\"`
